let  menproducts = [
    {
        id: 1,
        img: 'https://i.postimg.cc/KztZSxFX/ID-1.webp',
        for: 'Men',
        category: 'T-Shirt',
        description: 'Men Skull Print Tee',
        price: '142',
    },
    {
        id: 2,
        img: 'https://i.postimg.cc/yxvCsNbG/ID-2.webp',
        for: 'Men',
        category: 'T-Shirt',
        description: 'Men Playing Card Print Tee',
        price: '165',
    },
    {
        id: 3,
        img: 'https://i.postimg.cc/V6W3W6mN/ID-3.webp',
        for: 'Men',
        category: 'T-Shirt',
        description: 'Men Figure & Slogan Graphic Tee',
        price: '146',
    },
    {
        id: 4,
        img: 'https://i.postimg.cc/nrwS395n/ID-4.webp',
        for: 'Men',
        category: 'T-Shirt',
        description: 'Men Picture & Letter Graphic Tee',
        price: '152',
    },
    {
        id: 5,
        img: 'https://i.postimg.cc/Pf67X0q0/ID-5.webp',
        for: 'Men',
        category: 'T-Shirt',
        description: 'Men Cartoon Graphic Tee',
        price: '123',
    },
    {
        id: 6,
        img: 'https://i.postimg.cc/J4vdJJZq/ID-6.webp',
        for: 'Men',
        category: 'Jeans',
        description: 'Men Letter & Cartoon Patched Ripped Jeans',
        price: '433',
    },
    {
        id: 7,
        img: 'https://i.postimg.cc/1X4JV5z2/ID-7.webp',
        for: 'Men',
        category: 'Jeans',
        description: 'Men Ripped Washed Jeans',
        price: '391',
    },
    {
        id: 8,
        img: 'https://i.postimg.cc/cCKB499N/ID-8.webp',
        for: 'Men',
        category: 'Jeans',
        description: 'Men Ripped Washed Skinny Jeans',
        price: '361',
    },
    {
        id: 9,
        img: 'https://i.postimg.cc/sDh4kLGY/ID-9.webp',
        for: 'Men',
        category: 'Jeans',
        description: 'Men Straight Leg Jeans',
        price: '434',
    },
    {
        id: 10,
        img: 'https://i.postimg.cc/P5bzx84N/ID-10.webp',
        for: 'Men',
        category: 'Jeans',
        description: 'Men Two Tone Letter Embroidery Skinny Jeans',
        price: '409',
    },
    {
        id: 11,
        img: 'https://i.postimg.cc/9MkySPWg/ID-11.webp',
        for: 'Men',
        category: 'Jacket',
        description: 'Men Letter Patched Reflective Piping Trim Bomber Jacket Without Hoodie',
        price: '414',
    },
    {
        id: 12,
        img: 'https://i.postimg.cc/CdTkMFnj/ID-12.webp',
        for: 'Men',
        category: 'Jacket',
        description: 'SHEIN Men Striped Trim Letter Embroidered Suede Bomber Jacket',
        price: '520',
    },
    {
        id: 13,
        img: 'https://i.postimg.cc/s2D6Ccr3/ID-13.webp',
        for: 'Men',
        category: 'Jacket',
        description: 'Men 1pc Flap Pocket Drawstring Hooded Jacket',
        price: '442',
    },
    {
        id: 14,
        img: 'https://i.postimg.cc/50DnvWFt/ID-14.webp',
        for: 'Men',
        category: 'Jacket',
        description: 'Men Buffalo Plaid Print Teddy Bomber Jacket Without Hoodie',
        price: '418',
    },
    {
        id: 15,
        img: 'https://i.postimg.cc/TPFrNq27/ID-15.webp',
        for: 'Men',
        category: 'Jacket',
        description: 'Men Bear And Cartoon Graphic Flap Detail Denim Jacket Without Tee',
        price: '515',
    }
]

let womenproducts = [
    {
        id: 1,
        img: 'https://i.postimg.cc/mk3KVr4D/ID-1.webp',
        for: 'Women',
        category: 'Tshirt',
        description: 'Drop Shoulder Colorblock Top',
        price: '129',
    },
    {
        id: 2,
        img: 'https://i.postimg.cc/tJbM1H6H/ID-2.webp',
        for: 'Women',
        category: 'Tshirt',
        description: 'Butterfly Print Drop Shoulder Oversized Tee',
        price: '125',
    },
    {
        id: 3,
        img: 'https://i.postimg.cc/Pr2Rq9rB/ID-3.webp',
        for: 'Women',
        category: 'Tshirt',
        description: 'Letter Graphic Striped Trim Drop Shoulder Tee',
        price: '162',
    },
    {
        id: 4,
        img: 'https://i.postimg.cc/XvyHQvcb/ID-4.webp',
        for: 'Women',
        category: 'Tshirt',
        description: 'Letter & Expression Print Drop Shoulder Tee',
        price: '148',
    },
    {
        id: 5,
        img: 'https://i.postimg.cc/nrn3FG8F/ID-5.webp',
        for: 'Women',
        category: 'Tshirt',
        description: 'Letter & Floral Print Drop Shoulder Tee',
        price: '138',
    },
    {
        id: 6,
        img: 'https://i.postimg.cc/1z6BDjsR/ID-6.webp',
        for: 'Women',
        category: 'Jeans',
        description: 'Zipper Fly Tapered Jeans',
        price: '418',
    },
    {
        id: 7,
        img: 'https://i.postimg.cc/ydsmc6Ln/ID-7.webp',
        for: 'Women',
        category: 'Jeans',
        description: 'High Waist Straight Leg Ripped Jeans',
        price: '354',
    },
    {
        id: 8,
        img: 'https://i.postimg.cc/dtL88x9M/ID-8.webp',
        for: 'Women',
        category: 'Jeans',
        description: 'High Waist Skinny Cropped Jeans',
        price: '277',
    },
    {
        id: 9,
        img: 'https://i.postimg.cc/QtfT7Q9x/ID-9.webp',
        for: 'Women',
        category: 'Jeans',
        description: 'SHEIN SXY High Waisted Ripped Skinny Jeans',
        price: '368',
    },
    {
        id: 10,
        img: 'https://i.postimg.cc/k4gV721r/ID-10.webp',
        for: 'Women',
        category: 'Jeans',
        description: 'High Waist Ripped Skinny Jeans',
        price: '281',
    },
    {
        id: 11,
        img: 'https://i.postimg.cc/s2wXHVVT/ID-11.webp',
        for: 'Women',
        category: 'Jacket',
        description: 'Color-block Zip Up Drawstring Hem Jacket',
        price: '189',
    },
    {
        id: 12,
        img: 'https://i.postimg.cc/HWJwMN2q/ID-12.webp',
        for: 'Women',
        category: 'Jacket',
        description: 'Flap Pocket Drop Shoulder Drawstring Hooded Jacket',
        price: '318',
    },
    {
        id: 13,
        img: 'https://i.postimg.cc/0yCDx1kw/ID-13.webp',
        for: 'Women',
        category: 'Jacket',
        description: 'SHEIN PETITE Solid Zip Up Drawstring Crop Jacket',
        price: '211',
    },
    {
        id: 14,
        img: 'https://i.postimg.cc/MTgjtWDh/ID-14.webp',
        for: 'Women',
        category: 'Jacket',
        description: 'DAZY Striped Side Sleeve Hooded Teddy Jacket',
        price: '391',
    },
    {
        id: 15,
        img: 'https://i.postimg.cc/05m6P1Zy/ID-15.webp',
        for: 'Women',
        category: 'Jacket',
        description: 'Drop Shoulder Two Tone Crop Bomber Jacket',
        price: '195',
    }
]

let kidproducts = [
    {
        id: 1,
        img: 'https://i.postimg.cc/9FQrTwCr/ID-1.webp',
        for: 'Kids',
        category: 'Tshirt',
        description: 'Girls Car & Letter Graphic Tee',
        price: '93',
    },
    {
        id: 2,
        img: 'https://i.postimg.cc/Vk3637MC/ID-2.webp',
        for: 'Kids',
        category: 'Tshirt',
        description: 'SHEIN Girls Slogan Graphic Drop Shoulder Tee',
        price: '133',
    },
    {
        id: 3,
        img: 'https://i.postimg.cc/59ntx9L1/ID-3.webp',
        for: 'Kids',
        category: 'Tshirt',
        description: 'SHEIN Girls Letter Graphic Tee',
        price: '90',
    },
    {
        id: 4,
        img: 'https://i.postimg.cc/9f5mxD5P/ID-4.webp',
        for: 'Kids',
        category: 'Tshirt',
        description: 'SHEIN Girls Graphic Print Colorblock Asymmetrical Hem Tee',
        price: '112',
    },
    {
        id: 5,
        img: 'https://i.postimg.cc/Zq8TXJ4G/ID-5.webp',
        for: 'Kids',
        category: 'Tshirt',
        description: 'SHEIN Girls Car & Letter Graphic Tee',
        price: '115',
    },
    {
        id: 6,
        img: 'https://i.postimg.cc/pVGPwGML/ID-6.webp',
        for: 'Kids',
        category: 'Jeans',
        description: 'Boys Ripped Washed Tapered Jeans',
        price: '268',
    },
    {
        id: 7,
        img: 'https://i.postimg.cc/3NV5dq3j/ID-7.webp',
        for: 'Kids',
        category: 'Jeans',
        description: 'Boys Ripped Cat Scratch Washed Jeans',
        price: '384',
    },
    {
        id: 8,
        img: 'https://i.postimg.cc/sgCqq7x2/ID-8.webp',
        for: 'Kids',
        category: 'Jeans',
        description: 'SHEIN Boys Graphic Pattern Straight Leg Jeans',
        price: '258',
    },
    {
        id: 9,
        img: 'https://i.postimg.cc/YSCHDYDW/ID-9.webp',
        for: 'Kids',
        category: 'Jeans',
        description: 'SHEIN BASICS Boys Solid Straight Leg Jeans',
        price: '275',
    },
    {
        id: 10,
        img: 'https://i.postimg.cc/TYvXMZHG/ID-10.webp',
        for: 'Kids',
        category: 'Jeans',
        description: 'Boys Letter Graphic Bleach Wash Straight Leg Jeans',
        price: '263',
    },
    {
        id: 11,
        img: 'https://i.postimg.cc/2ypgYZGT/ID-11.webp',
        for: 'Kids',
        category: 'Jacket',
        description: 'SHEIN Girls Letter Tape Panel Colorblock Zipper Up Hooded Jacket',
        price: '272',
    },
    {
        id: 12,
        img: 'https://i.postimg.cc/rFk7Y5Kw/ID-12.webp',
        for: 'Kids',
        category: 'Jacket',
        description: 'SHEIN Girls Contrast Teddy Crop Jacket',
        price: '144',
    },
    {
        id: 13,
        img: 'https://i.postimg.cc/GpWXT1Dm/ID-13.webp',
        for: 'Kids',
        category: 'Jacket',
        description: 'SHEIN Boys Zip Up Thermal Lined Bomber Jacket',
        price: '353',
    },
    {
        id: 14,
        img: 'https://i.postimg.cc/1XPMMcJx/ID-14.webp',
        for: 'Kids',
        category: 'Jacket',
        description: 'Boys 1pc Letter Patched Striped Trim Bomber Jacket',
        price: '277',
    },
    {
        id: 15,
        img: 'https://i.postimg.cc/0yrntNdN/ID-15.webp',
        for: 'Kids',
        category: 'Jacket',
        description: 'Boys Letter Graphic Flap Pocket Denim Jacket Without Tee',
        price: '362',
    }
]